window.ow_emotes = {
 "Diversos":{
      "axl":{  
         "url":"https://i.imgur.com/eaYZ3m7.gif"
        },
	   "babby":{  
         "url":"https://i.imgur.com/u1O9yyD.png"
        },
	   "banger":{  
         "url":"https://i.imgur.com/1OSsdHD.gif"
      },
      "banger2":{  
         "url":"https://i.imgur.com/LwcEmSG.gif"
      },
      "banger3":{  
         "url":"https://i.imgur.com/5cezcWG.gif"
      },
       "banger4":{  
         "url":"https://i.imgur.com/MrtbDUW.gif"
      },
       "banger5":{  
         "url":"https://i.imgur.com/sQ9MBhG.gif"
      },
      "banger6":{  
         "url":"https://i.imgur.com/kX8eV8y.gif"
      },
	        "bravo":{  
         "url":"https://i.imgur.com/H37xWtB.gif"
      },
		"bob":{  
         "url":"https://i.imgur.com/yejRBgc.gif"
         },
		 "cage":{  
         "url":"https://i.imgur.com/MRbkpXW.gif"
        },
		 "cj": {
        "url": "https://i.imgur.com/32Nnqmc.png"
        },
	 	 "corey": {
        "url": "http://i.imgur.com/f6DW1V3.gif"
        },
	 	 "crazycow": {
        "url": "http://i.imgur.com/AQWcOlO.gif"
        },
		"damn":{
         "url":"https://i.imgur.com/muNvl6b.gif"
        },
		"darkness":{
      	"url":"https://i.imgur.com/xQLMoma.jpg"
      },
		"dirp":{  
         "url":"https://i.imgur.com/ZaC7iBS.jpg"
       },
	     "doge":{  
         "url":"https://i.imgur.com/9rQZdFj.jpg"
      },
	      "doge2":{  
         "url":"http://i.imgur.com/511cPBl.jpg"
      },
	       "eminem":{  
         "url":"http://i.imgur.com/Sr7ZRbi.gif"
      },
	       "eminem2":{  
         "url":"http://i.imgur.com/ObJbMI2.gif"
      },
	       "eminem3":{  
         "url":"http://i.imgur.com/Qwtx2n9.gif"
      },
	       "eminem4":{  
         "url":"http://i.imgur.com/4GRWSCh.gif"
      },
	        "facepalmgif":{  
         "url":"https://i.imgur.com/Jovv7R6.gif"
      },
	         "facepalmgif2":{  
         "url":"http://i.imgur.com/7Aevn10.gif"
      },
	        "feels":{  
         "url":"https://i.imgur.com/7pjGsQX.jpg"
      },
	"feels1":{
         "url":"https://i.imgur.com/rmj7p6s.jpg"
      },
      "feels2":{  
         "url":"https://i.imgur.com/huHTzIU.jpg"
      },
      "feels3":{  
         "url":"https://i.imgur.com/Px8fLIR.jpg"
      },
      "feels4":{  
         "url":"https://i.imgur.com/8nDfxyd.jpg"
      },
      "feels5":{  
         "url":"https://i.imgur.com/v4LUafF.jpg"
      },
      "feels6":{  
         "url":"https://i.imgur.com/rJxSX8W.jpg"
      },
      "feels7":{  
         "url":"https://i.imgur.com/ZBfVjRZ.jpg"
      },
      "feels8":{  
         "url":"https://i.imgur.com/V9cq9BT.jpg"
      },
      "feels9":{  
         "url":"https://i.imgur.com/pgP3EjB.jpg"
      },
	"feels10":{
         "url":"https://i.imgur.com/FFFOcFP.jpg"
      },
      "feelsbad":{  
         "url":"https://i.imgur.com/Io4Zvs3.jpg"
      },
      "feelsgif":{  
         "url":"https://i.imgur.com/GiOEYlD.gif"
      },
	        "feelsnigga":{
         "url":"https://i.imgur.com/OnzQsC7.jpg"
      },
      "feelsbro":{
         "url":"https://i.imgur.com/pWzA0Fi.gif"
      },
	   "gay":{  
         "url":"https://i.imgur.com/zXpqTDT.gif"
      },
	       "gandalf":{
      	"url":"https://i.imgur.com/QbVCQEa.gif"
      },
	        "god":{ 
      	"url":"https://i.imgur.com/YfG5u6F.gif"
      },
	    "hitler":{
         "url":"https://dl.dropboxusercontent.com/s/51kbxw8lcbv69b2/hitler.gif"
      },
	   "hiding":{  
       "url":"https://i.imgur.com/xJx2tpg.gif"
      },
      "haha":{
         "url":"https://i.imgur.com/yl2fr1z.gif"
      },
	   "heman":{  
         "url":"https://i.imgur.com/7UywzY4.gif"
      },
      "hhoo":{
         "url":"https://i.imgur.com/jGyKtjc.png"
      },
      "hhoogif":{
      	"url":"https://i.imgur.com/FOrMJt3.gif"
      },
	        "jason":{
         "url":"https://i.imgur.com/OrxWC9g.gif"
      },
       "lennyface":{  
         "url":"https://i.imgur.com/g4zRJ9C.jpg"
        },
      "terror":{
         "url":"https://i.imgur.com/mLInq4V.gif"
      },
      "terror2":{
         "url":"https://i.imgur.com/dE0gx7k.gif"
      },
      "terror3":{
         "url":"https://i.imgur.com/uBYvuGi.gif"
      },
      "terror4":{
         "url":"https://i.imgur.com/fb9caMi.gif"
      },
	      "jesuspalm":{  
         "url":"https://i.imgur.com/tx0DZfO.jpg"
      },
       "kappagif":{  
         "url":"https://i.imgur.com/ImGltes.gif"
      },
	  	"kim":{
         "url":"https://dl.dropboxusercontent.com/s/imaxuzsen111y3j/aplauso.gif"
      }, 
	        "lhama":{
         "url":"https://i.imgur.com/uUNdVs7.gif"
      },
	        "lennygif":{  
         "url":"https://i.imgur.com/OSdFEcj.gif"
      },
	    "mehmute":{  
         "url":"https://i.imgur.com/t6SN0IE.png"
      },
	        "mlg":{  
         "url":"https://i.imgur.com/vKXhX8b.gif"
      },
	    "michael":{
         "url":"https://dl.dropboxusercontent.com/s/zlqyshqmfnru8ko/michael.gif"
      },
	        "nyan":{  
         "url":"https://i.imgur.com/zkYnA9D.gif"
      },
	         "nerdpalm":{  
         "url":"https://i.imgur.com/nahfbMb.jpg"
       },
	        "nelson":{  
         "url":"https://i.imgur.com/8be9xVy.png"
      },
	        "notsureif":{  
         "url":"https://i.imgur.com/4jPyRG2.png"
      },
	        "okay":{  
         "url":"https://i.imgur.com/BpQWgTs.gif"
      },
	        "oh":{  
         "url":"https://i.imgur.com/OZRWuwJ.gif"
      },
	        "problem":{
         "url":"https://i.imgur.com/2B7A7ZK.png"
      },
	        "picard":{  
         "url":"https://i.imgur.com/CJSAWol.png"
      },
      "ponny2":{  
         "url":"https://i.imgur.com/KOADBQU.gif"
      },
	        "popcorn":{
         "url":"https://i.imgur.com/zQSiTYG.gif"
      },
	        "pepe":{
         "url":"https://i.imgur.com/ZNz8T3V.jpg"
      },
      "pepe2":{
         "url":"https://i.imgur.com/arwt3ny.jpg"
      },
      "rarepepe":{
         "url":"https://i.imgur.com/w2fwciR.gif"
      },
	 "relaxx":{
         "url":"http://i.imgur.com/I27tSTK.gif"
      },
	        "sax":{
      	"url":"https://i.imgur.com/FCrmC79.gif"
      },
	        "smoke":{
         "url":"https://i.imgur.com/OnNLzcA.gif"
      },
	        "surprise":{
         "url":"https://i.imgur.com/bdP6uzI.gif"
      },
	         "trap":{
         "url":"https://i.imgur.com/U2UGB8D.png"
      },
	     "tutstuts":{
         "url":"https://dl.dropboxusercontent.com/s/rnz9u2pmuqjsms1/tutstuts.gif"
      },
	        "ui":{
         "url":"https://i.imgur.com/se9HkCG.png"
      },
	  
	        "under":{  
         "url":"https://i.imgur.com/7qMVolj.gif"
      },
	        "vibe":{  
         "url":"https://i.imgur.com/w0xUqkt.gif"
      },
      "varg":{
         "height":"100px",
         "url":"https://i.imgur.com/MR59IZ9.png"
         "width":"100px"
      },
      "weed":{
         "url":"https://i.imgur.com/OwunEuJ.gif"
      },
      "will":{
         "url":"https://i.imgur.com/666sGQo.gif"
      },
	        "wills1":{
         "url":"https://i.imgur.com/bB7kIzm.png"
      },
      "wills2":{
         "url":"https://i.imgur.com/rUyDySG.png"
      },
      "wills3":{
         "url":"https://i.imgur.com/5nIIgVS.jpg"
      }
 },
 "Usuários Move-It": {
	 "branca":{  
         "url":"http://i.imgur.com/74j5fjs.png"
        },
	  "branca2":{  
         "url":"http://i.imgur.com/nBqyqw6.png"
        },
	 "dashing":{  
         "url":"http://i.imgur.com/vQ1zH67.png"
        },
	  "dashing2":{  
         "url":"http://i.imgur.com/YIwuvvi.jpg"
        },
	"dashing3":{  
         "url":"http://i.imgur.com/MLlTMgm.png"
        },
	 "dashing4":{  
         "url":"http://i.imgur.com/kY7o4Aq.jpg"
        },
	 "docinho":{  
         "url":"http://i.imgur.com/fvNhZhO.png"
        },
	 "duda":{  
         "url":"http://i.imgur.com/TkbPNGh.png"
        },
	 "eduarda":{  
         "url":"http://i.imgur.com/NRq4pTl.png"
        },
	 "eminemgay":{  
         "url":"http://i.imgur.com/2DjcwPv.png"
        },
	 "eduarda2":{  
         "url":"http://i.imgur.com/BJiJ9dg.png"
        },
	 "kaique":{  
         "url":"http://i.imgur.com/1456Jwi.jpg"
        },
	 "lucasbjj":{  
         "url":"http://i.imgur.com/EUtHGUE.jpg"
        },
	 "lucasbjj2":{  
         "url":"http://i.imgur.com/IJQOzQz.jpg"
        },
	 "psg2":{  
         "url":"http://i.imgur.com/4cu64NF.png"
        },
	 "psg3":{  
         "url":"http://i.imgur.com/rR4sU9e.jpg"
        },
	 "sabotage":{  
         "url":"http://i.imgur.com/DxkUpMG.png"
        },
	 "sabotage2":{  
         "url":"http://i.imgur.com/iYWsush.png"
        },
	"sabotage3":{  
         "url":"http://i.imgur.com/JzOVZRc.png"
        },
	 "sabotage4":{  
         "url":"http://i.imgur.com/axEb3yh.png"
        },
	 "seducao":{  
         "url":"http://i.imgur.com/ty2m2XM.png"
        },
	 "seducao2":{  
         "url":"http://i.imgur.com/vTZnnIe.jpg"
        },
	"seducao3":{  
         "url":"http://i.imgur.com/aKtHAct.png"
        },
	 "sid":{  
         "url":"http://i.imgur.com/bWl1eLM.jpg"
        },
	 "warlocked":{  
         "url":"http://i.imgur.com/bFy0SGJ.png"
        }
 },
 "Brasileiros": {
	      "ébixa":{  
         "url":"http://i.imgur.com/czixYkx.png"
        },
             "émermo":{  
         "url":"https://i.imgur.com/Ps0U7pW.gif"
        },
	   "émentira":{  
         "url":"https://i.imgur.com/JQEmF2m.gif"
        },
		"ésim":{  
         "url":"https://i.imgur.com/tALpIWp.jpg"
        },
		".v.":{  
         "url":"https://i.imgur.com/C79uctl.gif"
        },
		"100%":{  
         "url":"https://i.imgur.com/nhz07pH.jpg"
        },
		"acabou":{  
         "url":"https://imgur.com/vfN1hJq.jpg"
        },
		"agredi":{  
         "url":"https://i.imgur.com/JB7zmTi.png"
        },
	 	"alahu":{  
         "url":"https://i.imgur.com/dLU83pq.gif"
        },
		"anel":{  
         "url":"https://i.imgur.com/XoEFSNa.jpg"
        },
		"apunhala":{  
         "url":"https://i.imgur.com/nlscXR7.gif"
        },
	 	"applause":{  
         "url":"http://i.imgur.com/vOEYUC3.jpg"
        },
		"away":{  
         "url":"https://i.imgur.com/RzY8ev4.gif"
        },
		"baidu":{  
         "url":"https://i.imgur.com/nbdh0aA.jpg"
        },
		"ban":{  
         "url":"https://i.imgur.com/GqRd92T.jpg"
        },
	 	"ban2":{  
         "url":"http://i.imgur.com/tOXnNMn.jpg"
        },
		"bemloco":{  
         "url":"https://i.imgur.com/YQiKFHx.jpg"
        },
	 	"beijao":{  
         "url":"http://i.imgur.com/WNdTdRp.gif"
        },
		"bela":{  
         "url":"http://i.imgur.com/aCTWWKz.jpg"
        },
	 	"bemmacho":{  
         "url":"http://i.imgur.com/jv5l9Kb.png"
        },
	 	"bengala":{  
         "url":"http://i.imgur.com/XWES0xz.gif"
        },
		"berg":{  
         "url":"https://i.imgur.com/ZGBr0D1.png"
        },
		"bilada":{  
         "url":"https://i.imgur.com/P8atE5v.png"
        },
		"bino":{  
         "url":"https://i.imgur.com/eaYZ3m7.gif"
        },
		"bixao":{  
         "url":"https://i.imgur.com/Yu59ztU.png"
        },
		"bosta":{  
         "url":"https://i.imgur.com/cukzX3j.png"
        },
		"bory":{  
         "url":"http://i.imgur.com/E3wAKDa.gif"
        },
		"brasil":{  
         "url":"https://i.imgur.com/o43kLTx.jpg"
        },
		"brendan":{  
         "url":"https://i.imgur.com/4GMdSLZ.gif"
        },
		"burro":{  
         "url":"https://i.imgur.com/qle8kwP.gif"
        },
		"cachoeira":{  
         "url":"https://i.imgur.com/M0OKa03.png"
        },
	        "caradecu":{
	 "url":"http://i.imgur.com/zhn0D6L.png"
	},
		"caetano":{  
         "url":"https://i.imgur.com/4zuh99t.gif"
        },
		"café":{  
         "url":"https://i.imgur.com/lMWBD0j.png"
        },
		"caimbra":{  
         "url":"https://i.imgur.com/L4idMA8.gif"
        },
		"calmafera":{  
         "url":"https://i.imgur.com/ZvPsaZ7.jpg"
        },
		"carsampley":{  
         "url":"https://i.imgur.com/c1lqPLc.gif"
        },
		"cazalbe":{  
          "url":"https://dl.dropboxusercontent.com/s/cmdveivyf883e23/cazalbe.gif"
        },
		"cazalbe2":{  
         "url":"https://i.imgur.com/15XzVbp.jpg"
        },
	 	"cazalbe3":{  
         "url":"http://i.imgur.com/GaZMeSm.gif"
        },
		"chega":{  
         "url":"https://i.imgur.com/chizmUF.gif"
        },
		"chico":{  
         "url":"https://i.imgur.com/jTncWAZ.png"
        },
		"chola":{  
         "url":"https://i.imgur.com/UqwOG4q.gif"
        },
		"chora":{  
         "url":"https://i.imgur.com/hMZaAIg.gif"
        },
		"chora2":{  
         "url":"https://i.imgur.com/lc3SU60.gif"
        },
		"chora3":{  
         "url":"https://i.imgur.com/EtSFqhT.gif"
        },
		"chorei":{  
         "url":"https://i.imgur.com/hFFM8Pn.jpg"
        },
		"close1":{  
         "url":"https://i.imgur.com/SGzBFTp.gif"
        },
		"close2":{  
         "url":"https://i.imgur.com/Laq6SCL.gif"
        },
		"coração":{  
      	 "url":"https://i.imgur.com/stGYuBH.jpg"
        },
		"corre":{  
         "url":"https://i.imgur.com/LrT4c1X.jpg"
        },
		"costinha":{  
         "url":"https://i.imgur.com/K4x7UqI.gif"
        },
		"cryisfree":{  
         "url":"https://i.imgur.com/ZHj6lkY.png"
        },
		"cu":{  
         "url":"https://i.imgur.com/DGaDOyK.gif"
        },
	 	"dab":{  
         "url":"http://i.imgur.com/RSB9I90.gif"
        },
	        "davy":{
	 "url":"http://i.imgur.com/YDg0p1j.png"
	},
		"dança":{  
         "url":"https://i.imgur.com/E3dkL3t.gif"
        },
		"dança2":{  
         "url":"https://i.imgur.com/nre0Ptz.gif"
        },
		"dança3":{  
         "url":"https://i.imgur.com/rXviL4y.gif"
        },
		"dança4":{  
         "url":"https://i.imgur.com/sekxiqi.gif"
        },
		"dança5":{  
         "url":"http://i.imgur.com/8QnjShL.gif"
        },
		"dança6":{  
         "url":"http://i.imgur.com/1J2Rmf4.gif"
        },
		"dança7":{  
         "url":"http://i.imgur.com/lHrBhwU.gif"
        },
		"dança8":{  
         "url":"http://i.imgur.com/xAi5XWL.gif"
        },
	 	"dança9":{  
         "url":"http://i.imgur.com/XdSqpTM.gif"
        },
	 	"dança10":{  
         "url":"http://i.imgur.com/I7EKlSa.gif"
        },
	 	"dança11":{  
         "url":"http://i.imgur.com/ohGVaBH.gif"
        },
	 	"dança12":{  
         "url":"http://i.imgur.com/71FJDWi.gif"
        },
	 	"dança13":{  
         "url":"http://i.imgur.com/waok7dM.gif"
        },
	 	"dança14":{  
         "url":"http://i.imgur.com/7hBvXg6.gif"
        },
		"danada":{  
         "url":"https://i.imgur.com/jJotain.png"
        },
	 	"danada2":{  
         "url":"http://i.imgur.com/X3SBiav.png"
        },
		"dazero":{  
         "url":"https://i.imgur.com/88ADPRt.png"
        },
		"demencia":{  
         "url":"https://i.imgur.com/OUiQqjM.jpg"
        },
		"demente":{  
         "url":"https://i.imgur.com/hcFHm28.gif"
        },
		"deselegante":{  
         "url":"https://i.imgur.com/H8PJvmc.png"
        },
		"deselegante2":{  
         "url":"https://i.imgur.com/mvzHy3M.png"
        },
		"desgraça":{  
         "url":"https://i.imgur.com/erZNL5n.png"
        },
		"destruidora":{  
         "url":"https://i.imgur.com/d6jxPLi.gif"
        },
		"desu":{  
         "url":"https://i.imgur.com/Z5cg89l.png"
        },
		"desver":{  
         "url":"https://i.imgur.com/s5Q7YVs.jpg"
        },
		"dibre":{  
         "url":"https://i.imgur.com/oKyrjOv.png"
        },
		"dibre1":{  
         "url":"https://i.imgur.com/UZQjGlG.png"
        },
		"dilma":{  
         "url":"https://i.imgur.com/emL3hBV.png"
        },
		"dilma2":{  
         "url":"https://i.imgur.com/usdVJb3.jpg"
        },
		"dilma3":{  
         "url":"https://i.imgur.com/7eGFqGJ.jpg"
        },
		"dilma4":{  
         "url":"https://imgur.com/FdWAely.jpg"
        },
		"dilmapalm":{  
         "url":"https://i.imgur.com/Ub19Cm1.jpg"
        },
		"diney":{  
      	 "url":"https://i.imgur.com/6IN6Pxu.gif"
        },
		"dinossauro":{  
         "url":"https://i.imgur.com/T73QENt.png"
        },
		"dinossauro2":{  
         "url":"https://i.imgur.com/0nk9NBf.gif"
        },
		"dinossauro3":{  
         "url":"https://i.imgur.com/jD2sDdm.gif"
        },
		"diploma":{  
         "url":"https://i.imgur.com/aNySCx2.jpg"
        },
		"disseban":{  
         "url":"http://i.imgur.com/06d5o1R.jpg?1"
        },
		"disposta":{  
         "url":"https://imgur.com/7Xr6mJ5.jpg"
        },
		"diva":{  
         "url":"https://dl.dropboxusercontent.com/s/ordgqct09npvogd/diva.gif"
        },
		"dlç":{  
         "url":"https://i.imgur.com/OgwkZzo.png"
        },
		"dlç2":{  
         "url":"https://i.imgur.com/JZ8VKWc.jpg"
        },
		"dlç3":{  
         "url":"https://i.imgur.com/e445lXo.png"
        },
		"dlç4":{  
         "url":"https://i.imgur.com/EkOBJyT.png"
        },
		"dlç5":{  
      	 "url":"https://i.imgur.com/SnIVw8Q.jpg"
        },
		"dlçgif":{  
         "url":"https://i.imgur.com/1cU7mt3.gif"
        },
		"dlc":{  
         "url":"https://i.imgur.com/GIfMPSz.jpg"
        },
	 	"docil":{  
         "url":"http://i.imgur.com/4o2FglN.png"
        },
		"dollynho":{  
         "url":"https://i.imgur.com/66UwC9Q.jpg"
        },
		"dopado":{  
         "url":"https://i.imgur.com/DQI1o7D.gif"
        },
		"dragão":{  
         "url":"https://i.imgur.com/b79bIsm.png"
        },
	 	"drama":{  
         "url":"http://i.imgur.com/eelMT43.gif"
        },
		"dribe":{  
         "url":"https://i.imgur.com/IfVOE3J.jpg"
        },
		"dribe2":{  
         "url":"https://i.imgur.com/aUkbohX.jpg"
        },
		"dribe3":{  
         "url":"https://i.imgur.com/57FtsgX.jpg"
        },
		"dribe4":{  
      	 "url":"https://i.imgur.com/CjizyLK.jpg"
        },
		"empolgante":{  
         "url":"https://i.imgur.com/R3HHVD2.jpg"
        },
		"em":{  
         "url":"https://i.imgur.com/qlMQyza.jpg"
        },
		"emsm":{  
         "url":"https://i.imgur.com/aDhjPXx.jpg"
        },
		"emsme":{  
         "url":"https://i.imgur.com/pfQVT5U.jpg"
        },
		"engraçado":{  
         "url":"http://i.imgur.com/n6c80tr.jpg"
        },
		"erou":{  
         "url":"https://i.imgur.com/4wrakbp.jpg"
        },
		"euquis":{  
         "url":"https://i.imgur.com/iZdZPPd.jpg"
        },
		"fafa":{  
         "url":"https://i.imgur.com/m8ZopBV.gif"
        },
		"faleceu":{  
         "url":"https://i.imgur.com/vZE62y1.jpg"
        },
	 	"faustão":{  
         "url":"http://i.imgur.com/SX0OANN.gif"
        },
	 	"faustão2":{  
         "url":"http://i.imgur.com/9riYpDN.png"
        },
		"ficouoh":{  
         "url":"http://i.imgur.com/8y2SXIF.png"
        },
	 	"ficouoh":{  
         "url":"https://i.imgur.com/h1ZFm2P.jpg"
        },
		"foda-se":{  
         "url":"https://i.imgur.com/8pBXLn7.gif"
        },
		"foda-se2":{  
         "url":"https://i.imgur.com/bCYVoEx.jpg"
        },
		"foda-se3":{  
         "url":"https://i.imgur.com/0EfQWMN.jpg"
        },
		"foda-se4":{  
         "url":"http://i.imgur.com/X7HEXSX.png"
        },
		"foda.se":{  
         "url":"https://i.imgur.com/Ju4rLQA.jpg"
        },
		"fodace":{  
         "url":"https://i.imgur.com/mbHJvoR.gif"
        },
		"fodase":{  
         "url":"https://i.imgur.com/j1cSxm0.jpg"
        },
	 	"foderem":{  
         "url":"http://i.imgur.com/IiMER0v.jpg"
        },
		"fofão":{  
         "url":"https://i.imgur.com/8Mq3tPR.gif"
        },
		"freestep":{  
         "url":"https://i.imgur.com/bfDKHgM.gif"
        },
	 	"frio":{  
         "url":"http://i.imgur.com/noV17ej.png"
        },
		"gato":{  
         "url":"https://i.imgur.com/wRI10nK.gif"
        },
		"gente":{  
         "url":"https://i.imgur.com/ORjnzfn.jpg"
        },
		"graça":{  
         "url":"https://i.imgur.com/4f7LR3B.jpg"
        },
	 	"gstv":{  
         "url":"http://i.imgur.com/fju5hwW.jpg"
        },
	 	"gorila":{  
         "url":"http://i.imgur.com/uX0nWaU.png"
        },
	 	"gorila2":{  
         "url":"http://i.imgur.com/36YWez6.gif"
        },
	 	"gorila3":{  
         "url":"http://i.imgur.com/rHrINm6.jpg"
        },
	 	"hack":{  
         "url":"http://i.imgur.com/0jO2pig.png"
        },
		"hino":{  
         "url":"http://i.imgur.com/sued5LA.gif"
        },
		"hjn":{  
         "url":"https://i.imgur.com/SoZkcP3.jpg"
        },
		"hmm":{  
         "url":"https://i.imgur.com/ofTagdg.gif"
        },
		"hmm2":{  
         "url":"https://i.imgur.com/4PzgMep.jpg"
        },
		"hu3":{  
         "url":"https://i.imgur.com/wiQ0cyG.gif"
        },
		"hu3br":{  
         "url":"https://i.imgur.com/lM5EMUZ.jpg"
        },
		"huera":{  
         "url":"https://i.imgur.com/eGdbSgO.jpg"
        },
		"idai":{  
         "url":"https://i.imgur.com/OgHQCry.jpg"
        },
		"idiota":{  
         "url":"https://i.imgur.com/ocsGCQv.gif"
        },
		"infarto":{  
         "url":"https://i.imgur.com/3hvzwln.jpg"
        },
		"istudu":{  
         "url":"https://i.imgur.com/XuJbgWk.gif"
        },
		"jachega":{  
         "url":"https://i.imgur.com/aTmTdas.png"
        },
		"jailson":{  
         "url":"https://i.imgur.com/dVthkoQ.gif"
        },
		"jailson2":{  
         "url":"https://i.imgur.com/sLlX5B2.jpg"
        },
		"jailson3":{  
         "url":"https://i.imgur.com/XfJNTVs.jpg"
        },
		"jailson4":{  
         "url":"https://i.imgur.com/G08Oq6x.gif"
        },
	 	"jc":{  
         "url":"http://i.imgur.com/FR4MDmc.jpg"
        },
		"jureg":{  
         "url":"https://i.imgur.com/SDzmH3a.jpg"
        },
		"jureg2":{  
         "url":"http://i.imgur.com/3R2VGem.png"
        },
		"jureg3":{  
         "url":"https://i.imgur.com/V4Ly6IE.png"
        },
		"jureg4":{  
         "url":"http://i.imgur.com/Yb3TB0p.png"
        },
		"léostronda":{  
         "url":"https://i.imgur.com/tsv7zX4.png"
        },
		"legal":{  
         "url":"https://i.imgur.com/NAvDJFl.jpg"
        },
		"ler":{  
         "url":"https://i.imgur.com/dP3k6pR.jpg"
        },
		"linteressa":{  
         "url":"https://i.imgur.com/xhCO25z.gif"
        },
		"madruga":{  
         "url":"https://i.imgur.com/OvDq257.gif"
        },
	 		 "maigode":{
         "url":"https://i.imgur.com/6kZ4Br6.jpg"
        },
         "maigode2":{
         "url":"https://i.imgur.com/n79SjXm.jpg"
        },
		"mandanude":{  
         "url":"https://i.imgur.com/PTYLcye.png"
        },
	 	"mangueira":{  
         "url":"http://i.imgur.com/IqYEAAt.gif"
        },
	 	"mangueira2":{  
         "url":"http://i.imgur.com/g7UXP6Q.gif"
        },
	 	"mangueira3":{  
         "url":"http://i.imgur.com/xd7ehev.gif"
        },
	 	"mano":{  
         "url":"http://i.imgur.com/ppZPMUP.gif"
        },
		"marcelo":{  
          "url":"https://i.imgur.com/KJ7VuYX.jpg"
        },
		"marreco":{  
         "url":"http://i.imgur.com/VUZxXTX.jpg"
        },
	 	"marreco2":{  
         "url":"http://i.imgur.com/vkiUm47.jpg"
        },
		"marina":{  
         "url":"https://i.imgur.com/UHRpp4d.png"
        },
	 	"marinho":{  
         "url":"http://i.imgur.com/1fi0yJK.png"
        },
		"masc":{  
         "url":"https://i.imgur.com/O49ugVB.png"
        },
		"mehh":{  
         "url":"http://i.imgur.com/6lYPeQO.jpg"
        },
		"meobrigue":{  
         "url":"https://i.imgur.com/HrfUfMS.png"
        },
		"mizeravi":{  
         "url":"https://i.imgur.com/4ILWtwV.png"
        },
		"moitai":{  
         "url":"https://i.imgur.com/X379iNh.png"
        },
		"monalicia":{  
         "url":"https://i.imgur.com/35Jrx9b.png"
        },
		"monstrogif":{  
         "url":"https://i.imgur.com/15hqUd0.gif"
        },
		"morre":{  
         "url":"https://i.imgur.com/B100qjp.gif"
        },
		"morrison":{  
         "url":"https://i.imgur.com/6g3PA6d.gif"
        },
	 	"moveit":{  
         "url":"http://i.imgur.com/W5T4tUg.png"
        },
		"nãosei":{  
         "url":"https://i.imgur.com/QoPAHYd.png"
        },
		"nadave":{  
         "url":"https://i.imgur.com/IydoxRH.png"
        },
		"nao1":{  
         "url":"https://i.imgur.com/30Yl6Hk.jpg"
        },
		"nao":{  
         "url":"https://i.imgur.com/XGAXb3O.png"
        },
	 	"naosou":{  
         "url":"http://i.imgur.com/16p1fkD.gif"
        },
	 	"negan":{  
         "url":"http://i.imgur.com/QtsgSKT.gif"
        },
		"negócio":{  
         "url":"https://i.imgur.com/rPIhhjM.gif"
        },
		"nentendi":{  
         "url":"https://i.imgur.com/AcN6tOG.gif"
        },
	 	"nojo":{  
         "url":"http://i.imgur.com/Zcl8qPR.png"
        },
	 	"nojo2":{  
         "url":"http://i.imgur.com/KB96w7f.gif"
        },
		"nossa":{  
         "url":"https://i.imgur.com/FgrAWii.jpg"
        },
		"nudes":{  
         "url":"https://i.imgur.com/pvUWCt7.jpg"
        },
		"numsei":{  
         "url":"https://i.imgur.com/Hh0RnJH.gif"
        },
		"observo":{  
         "url":"https://i.imgur.com/XgDXpu5.gif"
        },
		"oco":{  
         "url":"https://i.imgur.com/QSBygqu.png"
        },
		"oco2":{  
         "url":"https://i.imgur.com/xOX01k3.jpg"
        },
		"okne":{  
         "url":"https://i.imgur.com/VkktMNz.gif"
        },
		"olha":{  
         "url":"https://i.imgur.com/5lKVDdL.png"
        },
		"olhaela":{  
         "url":"http://i.imgur.com/LV0jAeu.jpg"
        },
		"ovo":{  
         "url":"https://i.imgur.com/MojsPPc.gif"
        },
		"oxe":{  
         "url":"https://i.imgur.com/6m4EzlB.gif"
        },
		"ozzydeia":{  
         "url":"https://i.imgur.com/YCGImPN.jpg"
        },
		"pão":{  
         "url":"https://i.imgur.com/7TNXE0O.jpg"
        },
		"palhaço":{  
         "url":"https://i.imgur.com/k6D8MdT.png"
        },
		"parabains":{  
         "url":"https://i.imgur.com/biIoQe8.jpg"
        },
		"parede":{  
         "url":"https://i.imgur.com/deJHDnl.gif"
        },
	 	"patrão":{  
         "url":"http://i.imgur.com/U1gaFRq.png"
        },
		"pclixo":{  
         "url":"https://i.imgur.com/aVrNvoO.gif"
        },
		"penes":{  
         "url":"https://i.imgur.com/ypzUakJ.png"
        },
		"penes2":{  
         "url":"https://i.imgur.com/b3Vv0RI.png"
        },
		"pesquisa":{  
         "url":"https://i.imgur.com/hlOb17t.jpg"
        },
	 	"pilantra":{  
         "url":"http://i.imgur.com/vmqrvck.png"
        },
		"pingu":{  
         "url":"http://i.imgur.com/Nzn0ZXP.png"
        },
	 	"piscadinha":{  
         "url":"http://i.imgur.com/mQ67dTd.gif"
        },
		"pistola":{  
         "url":"https://i.imgur.com/Z9to5Nl.png"
        },
	 	"pistola2":{  
         "url":"http://i.imgur.com/rRKTtYP.gif"
        },
		"pnc":{  
         "url":"http://i.imgur.com/67U9AHV.jpg"
        },
		"pocaralho":{  
         "url":"https://i.imgur.com/NVgxpMW.jpg"
        },
		"poder":{  
         "url":"https://i.imgur.com/DxHp6Ey.jpg"
        },
		"poha":{  
         "url":"http://i.imgur.com/dJlhrZE.gif?1"
        },
		"popeye":{  
      	 "url":"https://i.imgur.com/HvCD34r.gif"
        },
		"porai":{  
         "url":"http://i.imgur.com/J6HBRW0.jpg"
        },
		"prerigo":{  
         "url":"https://i.imgur.com/rdzc9ca.png"
        },
		"providencia":{  
         "url":"https://i.imgur.com/HmB60BT.png"
        },
	 	"programa":{  
         "url":"http://i.imgur.com/G1Fnh5R.gif"
        },
	        "programa2":{
	 "url":"http://i.imgur.com/XwmJ8zl.gif"
	},		
		"psg":{  
         "url":"https://i.imgur.com/7DGHT1Z.jpg"
        },
		"punheta":{  
         "url":"http://i.imgur.com/1ytVUXI.jpg"
        },
	 	"punhetão":{  
         "url":"http://i.imgur.com/O4ExeEm.png"
        },
		"punheteiro":{  
         "url":"https://i.imgur.com/OVayNxL.png"
        },
		"putavida":{  
         "url":"https://i.imgur.com/dhnwM5I.gif"
        },
		"puto":{  
         "url":"https://i.imgur.com/v9h01r1.png"
        },
		"q":{  
         "url":"https://i.imgur.com/cZnygtn.jpg"
        },
		"q2":{  
         "url":"https://i.imgur.com/df4twj2.png"
        },
		"q3":{  
         "url":"http://i.imgur.com/C8fXWcb.jpg"
        },
	 	"quem":{  
         "url":"http://i.imgur.com/H9VThQG.gif"
        },
		"qponto":{  
         "url":"https://imgur.com/4NdIVTN.jpg"
        },
		"quelixo":{  
         "url":"https://i.imgur.com/g9IKzd1.jpg"
        },
		"queviaje":{  
         "url":"https://i.imgur.com/1Pp17HT.jpg"
        },
		"r10":{  
         "url":"https://i.imgur.com/yXY2KHX.jpg"
        },
		"r10secret":{  
         "url":"https://i.imgur.com/o0Ha07A.jpg"
        },
		"rapariga":{  
         "url":"https://i.imgur.com/puyTsuO.jpg"
        },
		"recalque":{  
         "url":"https://i.imgur.com/BvOMvP9.gif"
        },
		"referencia":{  
         "url":"http://i.imgur.com/SEfSWsq.jpg"
        },
		"rica":{  
         "url":"https://i.imgur.com/hzqgxR6.gif"
        },
	 	"risos":{  
         "url":"http://i.imgur.com/1FDa42O.gif"
        },
		"rosque":{  
         "url":"https://i.imgur.com/3bs2prg.jpg"
        },
		"sai":{  
         "url":"https://i.imgur.com/I80DvSW.png"
        },
	 	"silvio":{  
         "url":"http://i.imgur.com/kcLShhA.png"
        },
	 	"silvio2":{  
         "url":"http://i.imgur.com/0uOi1UU.png"
        },
	  	"silvio3":{  
         "url":"http://i.imgur.com/guDxj5c.png"
        },
	        "silvio4":{
	 "url":"http://i.imgur.com/5ysqApG.png"
	},
	        "silvio5":{
	 "url":"http://i.imgur.com/yL6RLI9.gif"
	},
		"saxguy":{  
         "url":"https://i.imgur.com/86nV3Ms.gif"
        },
		"sefoda":{  
         "url":"https://i.imgur.com/IDHE3Ve.gif"
        },
		"sefoda2":{  
         "url":"https://i.imgur.com/igDZYOt.gif"
        },
		"sefoda3":{  
         "url":"https://i.imgur.com/WcV2IVL.gif"
        },
		"sefodeu":{  
         "url":"https://i.imgur.com/S51VdIi.jpg"
        },
		"sefuder":{  
         "url":"https://i.imgur.com/34K5mb7.jpg"
        },
		"sexo":{  
         "url":"https://i.imgur.com/SXXcqnB.gif"
        },
	 	"sheldon":{  
         "url":"http://i.imgur.com/jMQIzhG.gif"
        },
		"sim":{  
         "url":"https://i.imgur.com/NL9o8ng.gif"
        },
		"strondou":{  
         "url":"https://i.imgur.com/18jBXx7.jpg"
        },
		"suicídio":{  
         "url":"https://i.imgur.com/SpsBBF8.jpg"
        },
		"tacerto":{  
         "url":"https://i.imgur.com/6dBnnKB.gif"
        },
		"tacry":{  
         "url":"https://i.imgur.com/WrYcJtP.jpg"
        },
		"tainá":{  
         "url":"https://i.imgur.com/umm8KTs.jpg"
        },
		"talento":{  
         "url":"https://i.imgur.com/qBikFj6.gif"
        },
		"taquerendo":{  
         "url":"https://dl.dropboxusercontent.com/s/q9i6gdl6f8ylepi/seicome.gif"
        },
		"tesão":{  
         "url":"https://i.imgur.com/I0NsPEe.jpg"
        },
		"tom":{  
         "url":"https://i.imgur.com/dLxtSmc.png"
        },
	 	"torcedor":{  
         "url":"http://i.imgur.com/ziiD7ZL.jpg"
        },
	 	"torcedor2":{  
         "url":"http://i.imgur.com/IngtJhI.png"
        },
		"treta":{  
         "url":"https://i.imgur.com/3XiQPSH.gif"
        },
	 	"treta2":{  
         "url":"http://i.imgur.com/CPnPfcN.png"
        },
		"uau":{  
         "url":"https://i.imgur.com/InFJRi3.gif"
        },
	 	"uau2":{  
         "url":"http://i.imgur.com/a78NgT2.gif"
        },
	 	"uou":{  
         "url":"http://i.imgur.com/ApD64WA.gif"
        },
		"util":{  
         "url":"https://i.imgur.com/InUkCys.gif"
        },
		"vai":{  
         "url":"https://i.imgur.com/rmxse7j.png"
        },
		"vaicry":{  
         "url":"https://i.imgur.com/05uFYdE.png"
        },
		"vaifodase":{  
         "url":"https://i.imgur.com/b3zJklr.jpg"
        },
		"vergonha":{  
         "url":"https://i.imgur.com/XF5PEKF.png"
        },
		"vergonha2":{  
         "url":"http://i.imgur.com/VfGcch7.jpg"
        },
		"viadão":{  
         "url":"https://i.imgur.com/t1YAxJp.jpg"
        },
		"viadão2":{  
         "url":"http://i.imgur.com/9ZfaeCS.png"
        },
		"viadão3":{  
         "url":"http://i.imgur.com/FpkrrMJ.png"
        },
		"viadão4":{  
         "url":"http://i.imgur.com/E8k4HrO.jpg"
        },
		"viadão5":{  
         "url":"http://i.imgur.com/SoDMUNv.png"
        },
		"viadão6":{  
         "url":"http://i.imgur.com/HbVBm9m.jpg"
        },
		"viadão7":{  
         "url":"http://i.imgur.com/WdEOT4n.png"
        },
		"viadão8":{  
         "url":"http://i.imgur.com/SuzvjHd.png"
        },
		"viadão9":{  
         "url":"http://i.imgur.com/mJpxSjk.gif"
        },
	 	"viadão10":{  
         "url":"http://i.imgur.com/10nyxoc.png"
        },
	 	"viadão11":{  
         "url":"http://i.imgur.com/lFKJNft.jpg"
        },
	 	"viadão12":{
         "url":"http://i.imgur.com/uiMB3uP.png"
        },
	 	"viadão13":{
         "url":"http://i.imgur.com/cCP0y6Y.png"
        },
	        "viadão14":{
	 "url":"http://i.imgur.com/ycNsLD1.png"
	},		
	        "viadãobonito":{
         "url":"https://i.imgur.com/zkO4uuS.jpg"
        },
		"viadagem":{ 
         "url":"https://i.imgur.com/wXmhCyx.png"
        },
	 	"você":{  
         "url":"http://i.imgur.com/S78vkw7.gif"
        },
	 	"war2":{  
         "url":"http://i.picasion.com/resize82/d066dde436bc158651ebb80bd85a2f97.gif"
        },
		"xablau":{  
         "url":"https://i.imgur.com/uEHQSrA.gif"
        },
		"zoeira":{  
         "url":"https://i.imgur.com/zVFnkQU.png"
        },
		"zoeiro":{  
         "url":"https://i.imgur.com/jBr1NaT.jpg"
        }
   },
	 "Futebol" : {
      "barcelona":{  
         "url":"https://i.imgur.com/OXc6mzV.png"
      },
      "sp":{  
         "url":"https://i.imgur.com/gSKtVby.png"
      },
      "cruzeiro":{  
         "url":"https://i.imgur.com/822pXUd.png"
      },
      "santos":{  
         "url":"https://i.imgur.com/MHvxHE3.png"
      },
      "realmadrid":{  
         "url":"https://i.imgur.com/Qjk3CHM.png"
      },
      "palmeiras":{  
         "url":"https://i.imgur.com/nXnIgUg.png"
      },
      "inter":{  
         "url":"https://i.imgur.com/1CAyN4A.png"
      },
      "flamengo":{  
         "url":"https://i.imgur.com/U8bzkTC.png"
      },
      "gremio":{  
         "url":"https://i.imgur.com/RIbNpmy.png"
      },
      "corinthians":{  
         "url":"https://i.imgur.com/VRIe1j5.png"
      }
  },
  "Música" : {
     "afrojack":{
        "url":"http://i.imgur.com/ZTL9rtk.png"
     },
     "alesso":{
        "url":"http://i.imgur.com/WV3UkiQ.png"
     },
     "arminvanbuuren":{
        "url":"http://i.imgur.com/1gi73aE.png"
     },
     "avicii":{
         "url":"http://i.imgur.com/Y7jwkMz.png"
      },
      "bassnation":{
         "url":"http://i.imgur.com/GYHVvIX.png"
      },
      "calvinharris":{
         "url":"http://i.imgur.com/oCGqAIz.png"
      },
      "deadmau5":{
         "url":"http://i.imgur.com/pM3id2o.png"
      },
      "dondiablo":{
         "url":"http://i.imgur.com/ks45L1M.png"
      },
      "edmcity":{
         "url":"http://i.imgur.com/xeppKAf.png"
      },
      "hardwell":{
         "url":"http://i.imgur.com/vbovXXJ.png"
      },
      "kdrew":{
         "url":"http://i.imgur.com/aNq3yFr.png"
      },
      "knifeparty":{
         "url":"http://i.imgur.com/XTiGAbN.png"
      },
      "krewella":{
         "url":"http://i.imgur.com/Bmh536K.png"
      },
      "martingarrix":{
         "url":"http://i.imgur.com/uFPUJbD.png"
      },
      "ncs":{
         "url":"http://i.imgur.com/DCp0j66.png"
      },
      "nervo":{
         "url":"http://i.imgur.com/Bl4fA7p.png"
      },
      "nickyromero":{
         "url":"http://i.imgur.com/Y2M7C5Y.png"
      },
      "davidguetta":{
         "url":"http://i.imgur.com/YG3L9Zn.png"
      },
      "plugdj":{
         "url":"http://i.imgur.com/e5ZTfvj.png"
      },
      "proximity":{
         "url":"http://i.imgur.com/QSdXIPY.png"
      },
      "rehab":{
         "url":"http://i.imgur.com/0IXROCz.png"
      },
      "showtek":{
         "url":"http://i.imgur.com/Sky8x4t.png"
      },
      "skrillex":{
         "url":"http://i.imgur.com/FeWO8PB.png"
      },
      "steveaoki":{
         "url":"http://i.imgur.com/V2DKyGR.png"
      },
      "prodigy":{
         "url":"http://i.imgur.com/aTK722r.png"
      },
      "tiesto":{
         "url":"http://i.imgur.com/oD4IarB.png"
      },
      "trapcity":{
         "url":"http://i.imgur.com/Z2cX62i.png"
      },
      "virtualriot":{
         "url":"http://i.imgur.com/b57tQFx.png"
      },
      "zedd":{
         "url":"http://i.imgur.com/6aJ09Bl.png"
      },
      "zomboy":{
         "url":"http://i.imgur.com/UHNZvFl.png"
      },
      "ladygaga":{
         "url":"http://i.imgur.com/B9t4plI.png"
      },
      "passenger":{
         "url":"http://i.imgur.com/C1lxN54.png"
      },
      "raego":{
         "url":"http://i.imgur.com/MWXHels.png"
      }
   }
};
