window.ow_emotes = {
 "Diversos":{
      "axl":{  
         "height":"100px",
         "url":"https://i.imgur.com/eaYZ3m7.gif",
         "width":"120px"
        },
	   "babby":{  
         "height":"35px",
         "url":"https://i.imgur.com/u1O9yyD.png",
         "width":"25px"
        },
	   "banger":{  
         "url":"https://i.imgur.com/1OSsdHD.gif",
         "width":"110px",
         "height":"110px"
      },
      "banger2":{  
         "url":"https://i.imgur.com/LwcEmSG.gif",
         "width":"150px",
         "height":"120px"
      },
      "banger3":{  
         "url":"https://i.imgur.com/5cezcWG.gif",
         "width":"120px",
         "height":"120px"
      },
       "banger4":{  
         "url":"https://i.imgur.com/MrtbDUW.gif",
         "width":"150px",
         "height":"120px"
      },
       "banger5":{  
         "url":"https://i.imgur.com/sQ9MBhG.gif",
         "width":"120px",
         "height":"150px"
      },
      "banger6":{  
         "url":"https://i.imgur.com/kX8eV8y.gif",
         "width":"130px",
         "height":"120px"
      },
	        "bravo":{  
         "height":"120px",
         "url":"https://i.imgur.com/H37xWtB.gif",
         "width":"90px"
      },
		"bob":{  
         "height":"50px",
         "url":"https://i.imgur.com/yejRBgc.gif",
         "width":"50px"
         },
		 "cage":{  
         "height":"70px",
         "url":"https://i.imgur.com/MRbkpXW.gif",
         "width":"128px"
        },
		 "cj": {
        "height": "48px",
        "width": "38px",
        "url": "https://i.imgur.com/32Nnqmc.png",
        },
		"damn":{
         "height":"90px",
         "url":"https://i.imgur.com/muNvl6b.gif",
         "width":"160px"
        },
		"darkness":{
      	"width":"187px",
      	"height":"142px",
      	"url":"https://i.imgur.com/xQLMoma.jpg",
      },
		"dirp":{  
         "url":"https://i.imgur.com/ZaC7iBS.jpg",
         "width":"51px",
         "height":"49px"
       },
	     "doge":{  
         "url":"https://i.imgur.com/9rQZdFj.jpg",
         "width":"89px",
         "height":"86px"
      },
	      "doge2":{  
         "url":"http://i.imgur.com/511cPBl.jpg",
         "width":"94px",
         "height":"90px"
      },
	        "facepalmgif":{  
         "height":"92px",
         "url":"https://i.imgur.com/Jovv7R6.gif",
         "width":"130px"
      },
	        "feels":{  
         "height":"75px",
         "url":"https://i.imgur.com/7pjGsQX.jpg",
         "width":"65px"
      },
	"feels1":{
         "height":"120px",
         "url":"https://i.imgur.com/rmj7p6s.jpg",
         "width":"100px"
      },
      "feels2":{  
         "height":"93px",
         "url":"https://i.imgur.com/huHTzIU.jpg",
         "width":"75px"
      },
      "feels3":{  
         "height":"97px",
         "url":"https://i.imgur.com/Px8fLIR.jpg",
         "width":"94px"
      },
      "feels4":{  
         "height":"95px",
         "url":"https://i.imgur.com/8nDfxyd.jpg",
         "width":"82px"
      },
      "feels5":{  
         "height":"103px",
         "url":"https://i.imgur.com/v4LUafF.jpg",
         "width":"103px"
      },
      "feels6":{  
         "height":"73px",
         "url":"https://i.imgur.com/rJxSX8W.jpg",
         "width":"104px"
      },
      "feels7":{  
         "height":"104px",
         "url":"https://i.imgur.com/ZBfVjRZ.jpg",
         "width":"83px"
      },
      "feels8":{  
         "height":"111px",
         "url":"https://i.imgur.com/V9cq9BT.jpg",
         "width":"87px"
      },
      "feels9":{  
         "height":"90px",
         "url":"https://i.imgur.com/pgP3EjB.jpg",
         "width":"99px"
      },
	"feels10":{
         "height":"92px",
         "url":"https://i.imgur.com/FFFOcFP.jpg",
         "width":"90px"
      },
      "feelsbad":{  
         "url":"https://i.imgur.com/Io4Zvs3.jpg",
         "width":"73px",
         "height":"73px"
      },
      "feelsgif":{  
         "url":"https://i.imgur.com/GiOEYlD.gif",
         "width":"160px",
         "height":"100px"
      },
	        "feelsnigga":{
         "height":"100px",
         "url":"https://i.imgur.com/OnzQsC7.jpg",
         "width":"100px"
      },
      "feelsbro":{
         "height":"120px",
         "url":"https://i.imgur.com/pWzA0Fi.gif",
         "width":"150px"
      },
	   "gay":{  
         "height":"80px",
         "url":"https://i.imgur.com/zXpqTDT.gif",
         "width":"120px"
      },
	       "gandalf":{
      	"width":"140px",
      	"height":"70px",
      	"url":"https://i.imgur.com/QbVCQEa.gif",
      },
	        "god":{ 
      	"url":"https://i.imgur.com/YfG5u6F.gif",
      	"width":"120px",
      	"height":"90px"
      },
	    "hitler":{
         "url":"https://dl.dropboxusercontent.com/s/51kbxw8lcbv69b2/hitler.gif",
         "width":"81px",
         "height":"100px"
      },
	   "hiding":{  
       "url":"https://i.imgur.com/xJx2tpg.gif",
       "width":"107px",
       "height":"80px"
      },
      "haha":{
         "height":"71px",
         "url":"https://i.imgur.com/yl2fr1z.gif",
         "width":"128px"
      },
	   "heman":{  
         "url":"https://i.imgur.com/7UywzY4.gif",
         "width":"70px",
         "height":"48px"
      },
      "hhoo":{
         "url":"https://i.imgur.com/jGyKtjc.png",
         "width":"160px",
         "height":"90px"
      },
      "hhoogif":{
      	"url":"https://i.imgur.com/FOrMJt3.gif",
      	"width":"120px",
      	"height":"90px"
      },
	        "jason":{
         "height":"120px",
         "url":"https://i.imgur.com/OrxWC9g.gif",
         "width":"120px"
      },
      "terror":{
         "height":"120px",
         "url":"https://i.imgur.com/mLInq4V.gif",
         "width":"120px"
      },
      "terror2":{
         "height":"100px",
         "url":"https://i.imgur.com/dE0gx7k.gif",
         "width":"130px"
      },
      "terror3":{
         "height":"120px",
         "url":"https://i.imgur.com/uBYvuGi.gif",
         "width":"120px"
      },
      "terror4":{
         "height":"100px",
         "url":"https://i.imgur.com/fb9caMi.gif",
         "width":"120px"
      },
	      "jesuspalm":{  
         "url":"https://i.imgur.com/tx0DZfO.jpg",
         "width":"83px",
         "height":"74px"
      },
       "kappagif":{  
         "url":"https://i.imgur.com/ImGltes.gif",
         "width":"40px",
         "height":"50px"
      },
	  	"kim":{
         "url":"https://dl.dropboxusercontent.com/s/imaxuzsen111y3j/aplauso.gif",
         "width":"104px",
         "height":"80px"
      }, 
	        "lhama":{
         "height":"107px",
         "url":"https://i.imgur.com/uUNdVs7.gif",
         "width":"120px"
      },
	        "lennygif":{  
         "height":"90px",
         "url":"https://i.imgur.com/OSdFEcj.gif",
         "width":"104px"
      },
	    "mehmute":{  
         "height":"100px",
         "url":"https://i.imgur.com/t6SN0IE.png",
         "width":"120px"
      },
	        "mlg":{  
         "height":"94px",
         "url":"https://i.imgur.com/vKXhX8b.gif",
         "width":"94px"
      },
	    "michael":{
         "url":"https://dl.dropboxusercontent.com/s/zlqyshqmfnru8ko/michael.gif",
         "width":"104px",
         "height":"68px"
      },
	        "nyan":{  
         "height":"50px",
         "url":"https://i.imgur.com/zkYnA9D.gif",
         "width":"50px"
      },
	         "nerdpalm":{  
         "url":"https://i.imgur.com/nahfbMb.jpg",
         "width":"120px",
         "height":"100px"
       },
	        "nelson":{  
         "height":"90px",
         "url":"https://i.imgur.com/8be9xVy.png",
         "width":"120px"
      },
	        "notsureif":{  
         "height":"82px",
         "url":"https://i.imgur.com/4jPyRG2.png",
         "width":"81px"
      },
	        "okay":{  
         "height":"50px",
         "url":"https://i.imgur.com/BpQWgTs.gif",
         "width":"50px"
      },
	        "oh":{  
         "url":"https://i.imgur.com/OZRWuwJ.gif",
         "width":"104px",
         "height":"50px"
      },
	        "problem":{
         "height":"79px",
         "url":"https://i.imgur.com/2B7A7ZK.png",
         "width":"67px"
      },
	        "picard":{  
         "height":"88px",
         "url":"https://i.imgur.com/CJSAWol.png",
         "width":"124px"
      },
      "ponny2":{  
         "height":"50px",
         "url":"https://i.imgur.com/KOADBQU.gif",
         "width":"50px"
      },
	        "popcorn":{
         "height":"90px",
         "url":"https://i.imgur.com/zQSiTYG.gif",
         "width":"118px"
      },
	        "pepe":{
         "height":"90px",
         "url":"https://i.imgur.com/ZNz8T3V.jpg",
         "width":"90px"
      },
      "pepe2":{
         "height":"90px",
         "url":"https://i.imgur.com/arwt3ny.jpg",
         "width":"90px"
      },
      "rarepepe":{
         "height":"120px",
         "url":"https://i.imgur.com/w2fwciR.gif",
         "width":"120px"
      },
	        "sax":{
      	"width":"123px",
      	"height":"92px",
      	"url":"https://i.imgur.com/FCrmC79.gif"
      },
	        "smoke":{
         "height":"71px",
         "url":"https://i.imgur.com/OnNLzcA.gif",
         "width":"35px"
      },
	        "surprise":{
         "url":"https://i.imgur.com/bdP6uzI.gif",
         "width":"102px",
         "height":"76px"
      },
	         "trap":{
         "url":"https://i.imgur.com/U2UGB8D.png",
         "width":"102px",
         "height":"90px"
      },
	     "tutstuts":{
         "url":"https://dl.dropboxusercontent.com/s/rnz9u2pmuqjsms1/tutstuts.gif",
         "width":"80px",
         "height":"54px"
      },
	        "ui":{
         "height":"35px",
         "url":"https://i.imgur.com/se9HkCG.png",
         "width":"31px"
      },
	  
	        "under":{  
         "url":"https://i.imgur.com/7qMVolj.gif",
         "width":"120px",
         "height":"120px"
      },
	        "vibe":{  
         "url":"https://i.imgur.com/w0xUqkt.gif",
         "width":"70px",
         "height":"48px"
      },
      "varg":{
         "height":"100px",
         "url":"https://i.imgur.com/MR59IZ9.png",
         "width":"100px"
      },
      "weed":{
         "height":"94px",
         "url":"https://i.imgur.com/OwunEuJ.gif",
         "width":"125px"
      },
      "will":{
         "url":"https://i.imgur.com/666sGQo.gif",
         "width":"130px",
         "height":"70px"
      },
	        "wills1":{
         "height":"79px",
         "url":"https://i.imgur.com/bB7kIzm.png",
         "width":"89px"
      },
      "wills2":{
         "height":"79px",
         "url":"https://i.imgur.com/rUyDySG.png",
         "width":"89px"
      },
      "wills3":{
         "height":"100px",
         "url":"https://i.imgur.com/5nIIgVS.jpg",
         "width":"100px"
      }
 },
 "Brasileiros": {
             "émermo":{  
         "height":"90px",
         "url":"https://i.imgur.com/Ps0U7pW.gif",
         "width":"120px"
        },
	   "émentira":{  
         "height":"80px",
         "url":"https://i.imgur.com/JQEmF2m.gif",
         "width":"96px"
        },
		"ésim":{  
         "url":"https://i.imgur.com/tALpIWp.jpg",
         "width":"109px",
         "height":"70px"
        },
		".v.":{  
         "height":"64px",
         "url":"https://i.imgur.com/C79uctl.gif",
         "width":"120px"
        },
		"100%":{  
         "height":"49px",
         "url":"https://i.imgur.com/nhz07pH.jpg",
         "width":"156px"
        },
		"acabou":{  
         "height":"100px",
         "url":"https://imgur.com/vfN1hJq.jpg",
         "width":"135px"
        },
		"agredi":{  
         "url":"https://i.imgur.com/JB7zmTi.png",
         "width":"185px",
         "height":"104px"
        },
		"anel":{  
         "height":"100px",
         "url":"https://i.imgur.com/XoEFSNa.jpg",
         "width":"90px"
        },
		"apunhala":{  
         "height":"100px",
         "url":"https://i.imgur.com/nlscXR7.gif",
         "width":"120px"
        },
		"away":{  
         "height":"88px",
         "url":"https://i.imgur.com/RzY8ev4.gif",
         "width":"104px"
        },
		"baidu":{  
         "url":"https://i.imgur.com/nbdh0aA.jpg",
         "width":"60px",
         "height":"60px"
        },
		"ban":{  
         "url":"https://i.imgur.com/GqRd92T.jpg",
         "width":"120px",
         "height":"100px"
        },
		"bemloco":{  
         "height":"75px",
         "url":"https://i.imgur.com/YQiKFHx.jpg",
         "width":"64px"
        },
		"bela":{  
         "height":"105px",
         "url":"http://i.imgur.com/aCTWWKz.jpg",
         "width":"79px"
        },
		"berg":{  
         "height":"90px",
         "url":"https://i.imgur.com/ZGBr0D1.png",
         "width":"120px"
        },
		"bilada":{  
         "url":"https://i.imgur.com/P8atE5v.png",
         "width":"60px",
         "height":"60px"
        },
		"bino":{  
         "height":"80px",
         "url":"https://i.imgur.com/eaYZ3m7.gif",
         "width":"80px"
        },
		"bixao":{  
         "height":"100px",
         "url":"https://i.imgur.com/Yu59ztU.png",
         "width":"90px"
        },
		"bosta":{  
         "url":"https://i.imgur.com/cukzX3j.png",
         "width":"120px",
         "height":"90px"
        },
		"bory":{  
         "height":"79px",
         "url":"http://i.imgur.com/E3wAKDa.gif",
         "width":"140px"
        },
		"brasil":{  
         "height":"74px",
         "url":"https://i.imgur.com/o43kLTx.jpg",
         "width":"112px"
        },
		"brendan":{  
         "height":"150px",
         "url":"https://i.imgur.com/4GMdSLZ.gif",
         "width":"100px"
        },
		"burro":{  
         "height":"90px",
         "url":"https://i.imgur.com/qle8kwP.gif",
         "width":"120px"
        },
		"cachoeira":{  
         "height":"89px",
         "url":"https://i.imgur.com/M0OKa03.png",
         "width":"120px"
        },
		"caetano":{  
         "height":"90px",
         "url":"https://i.imgur.com/4zuh99t.gif",
         "width":"120px"
        },
		"café":{  
         "height":"81px",
         "url":"https://i.imgur.com/lMWBD0j.png",
         "width":"104px"
        },
		"caimbra":{  
         "height":"90px",
         "url":"https://i.imgur.com/L4idMA8.gif",
         "width":"120px"
        },
		"calmafera":{  
         "height":"95px",
         "url":"https://i.imgur.com/ZvPsaZ7.jpg",
         "width":"103px"
        },
		"carsampley":{  
         "height":"100px",
         "url":"https://i.imgur.com/c1lqPLc.gif",
         "width":"178px"
        },
		"cazalbe":{  
          "url":"https://dl.dropboxusercontent.com/s/cmdveivyf883e23/cazalbe.gif",
         "width":"80px",
         "height":"54px"
        },
		"cazalbe2":{  
         "url":"https://i.imgur.com/15XzVbp.jpg",
         "width":"66px",
         "height":"56px"
        },
	 	"cazalbe3":{  
         "url":"http://i.imgur.com/GaZMeSm.gif",
         "width":"120px",
         "height":"160px"
        },
		"chega":{  
         "url":"https://i.imgur.com/chizmUF.gif",
         "width":"130px",
         "height":"56px"
        },
		"chico":{  
         "url":"https://i.imgur.com/jTncWAZ.png",
         "width":"28px",
         "height":"28px"
        },
		"chola":{  
         "url":"https://i.imgur.com/UqwOG4q.gif",
         "width":"104px",
         "height":"75px"
        },
		"chora":{  
         "height":"90px",
         "url":"https://i.imgur.com/hMZaAIg.gif",
         "width":"160px"
        },
		"chora2":{  
         "url":"https://i.imgur.com/lc3SU60.gif",
         "width":"120px",
         "height":"120px"
        },
		"chora3":{  
         "height":"150px",
         "url":"https://i.imgur.com/EtSFqhT.gif",
         "width":"120px"
        },
		"chorei":{  
         "height":"88px",
         "url":"https://i.imgur.com/hFFM8Pn.jpg",
         "width":"104px"
        },
		"close1":{  
         "height":"120px",
         "url":"https://i.imgur.com/SGzBFTp.gif",
         "width":"120px"
        },
		"close2":{  
         "height":"150px",
         "url":"https://i.imgur.com/Laq6SCL.gif",
         "width":"150px"
        },
		"coração":{  
         "width":"90px",
      	 "height":"90px",
      	 "url":"https://i.imgur.com/stGYuBH.jpg",
        },
		"corre":{  
         "url":"https://i.imgur.com/LrT4c1X.jpg",
         "width":"120px",
         "height":"120px"
        },
		"costinha":{  
         "height":"82px",
         "url":"https://i.imgur.com/K4x7UqI.gif",
         "width":"102px"
        },
		"cryisfree":{  
         "url":"https://i.imgur.com/ZHj6lkY.png",
         "width":"104px",
         "height":"50px"
        },
		"cu":{  
         "height":"92px",
         "url":"https://i.imgur.com/DGaDOyK.gif",
         "width":"123px"
        },
		"dança":{  
         "url":"https://i.imgur.com/E3dkL3t.gif",
         "width":"60px",
         "height":"85px"
        },
		"dança2":{  
         "url":"https://i.imgur.com/nre0Ptz.gif",
         "width":"150px",
         "height":"100px"
        },
		"dança3":{  
         "url":"https://i.imgur.com/rXviL4y.gif",
         "width":"120px",
         "height":"120px"
        },
		"dança4":{  
         "url":"https://i.imgur.com/sekxiqi.gif",
         "width":"150px",
         "height":"100px"
        },
		"dança5":{  
         "height":"130px",
         "url":"http://i.imgur.com/8QnjShL.gif",
         "width":"60px"
        },
		"dança6":{  
         "height":"103px",
         "url":"http://i.imgur.com/1J2Rmf4.gif",
         "width":"185px"
        },
		"dança7":{  
         "height":"103px",
         "url":"http://i.imgur.com/lHrBhwU.gif",
         "width":"185px"
        },
		"dança8":{  
         "height":"111px",
         "url":"http://i.imgur.com/xAi5XWL.gif",
         "width":"135px"
        },
		"danada":{  
         "height":"100px",
         "url":"https://i.imgur.com/jJotain.png",
         "width":"100px"
        },
	 	"danada2":{  
         "height":"116px",
         "url":"http://i.imgur.com/X3SBiav.png",
         "width":"143px"
        },
		"dazero":{  
         "url":"https://i.imgur.com/88ADPRt.png",
         "width":"110px",
         "height":"85px"
        },
		"demencia":{  
         "height":"57px",
         "url":"https://i.imgur.com/OUiQqjM.jpg",
         "width":"85px"
        },
		"demente":{  
         "url":"https://i.imgur.com/hcFHm28.gif",
         "width":"110px",
         "height":"63px"
        },
		"deselegante":{  
         "height":"89px",
         "url":"https://i.imgur.com/H8PJvmc.png",
         "width":"118px"
        },
		"deselegante2":{  
         "height":"90px",
         "url":"https://i.imgur.com/mvzHy3M.png",
         "width":"88px"
        },
		"desgraça":{  
         "height":"74px",
         "url":"https://i.imgur.com/erZNL5n.png",
         "width":"93px"
        },
	 	"dashing":{  
         "height":"59px",
         "url":"http://i.imgur.com/jh3akVl.png",
         "width":"334px"
        },
		"destruidora":{  
         "url":"https://i.imgur.com/d6jxPLi.gif",
         "width":"120px",
         "height":"80px"
        },
		"desu":{  
         "url":"https://i.imgur.com/Z5cg89l.png",
         "width":"120px",
         "height":"90px"
        },
		"desver":{  
         "url":"https://i.imgur.com/s5Q7YVs.jpg",
         "width":"103px",
         "height":"48px"
        },
		"dibre":{  
         "url":"https://i.imgur.com/oKyrjOv.png",
         "width":"122px",
         "height":"90px"
        },
		"dibre1":{  
         "url":"https://i.imgur.com/UZQjGlG.png",
         "width":"139px",
         "height":"104px"
        },
		"dilma":{  
         "height":"79px",
         "url":"https://i.imgur.com/emL3hBV.png",
         "width":"89px"
        },
		"dilma2":{  
         "height":"78px",
         "url":"https://i.imgur.com/usdVJb3.jpg",
         "width":"89px"
        },
		"dilma3":{  
         "height":"78px",
         "url":"https://i.imgur.com/7eGFqGJ.jpg",
         "width":"89px"
        },
		"dilma4":{  
         "height":"100px",
         "url":"https://imgur.com/FdWAely.jpg",
         "width":"135px"
        },
		"dilmapalm":{  
         "height":"78px",
         "url":"https://i.imgur.com/Ub19Cm1.jpg",
         "width":"89px"
        },
		"diney":{  
         "width":"123px",
      	 "height":"92px",
      	 "url":"https://i.imgur.com/6IN6Pxu.gif",
        },
		"dinossauro":{  
         "url":"https://i.imgur.com/T73QENt.png",
         "width":"95px",
         "height":"88px"
        },
		"dinossauro2":{  
         "url":"https://i.imgur.com/0nk9NBf.gif",
         "width":"104px",
         "height":"84px"
        },
		"dinossauro3":{  
         "url":"https://i.imgur.com/jD2sDdm.gif",
         "width":"136px",
         "height":"122px"
        },
		"diploma":{  
         "height":"90px",
         "url":"https://i.imgur.com/aNySCx2.jpg",
         "width":"130px"
        },
		"disseban":{  
         "height":"80px",
         "url":"http://i.imgur.com/06d5o1R.jpg?1",
         "width":"120px"
        },
		"disposta":{  
         "height":"100px",
         "url":"https://imgur.com/7Xr6mJ5.jpg",
         "width":"100px"
        },
		"diva":{  
         "url":"https://dl.dropboxusercontent.com/s/ordgqct09npvogd/diva.gif",
         "width":"104px",
         "height":"104px"
        },
		"dlç":{  
         "url":"https://i.imgur.com/OgwkZzo.png",
         "width":"28px",
         "height":"28px"
        },
		"dlç2":{  
         "url":"https://i.imgur.com/OgwkZzo.png",
         "width":"28px",
         "height":"28px"
        },
		"dlç3":{  
         "url":"https://i.imgur.com/e445lXo.png",
         "width":"123px",
         "height":"75px"
        },
		"dlç4":{  
         "url":"https://i.imgur.com/EkOBJyT.png",
         "width":"70px",
         "height":"70px"
        },
		"dlç5":{  
         "width":"90px",
      	 "height":"90px",
      	 "url":"https://i.imgur.com/SnIVw8Q.jpg",
        },
		"dlçgif":{  
         "url":"https://i.imgur.com/1cU7mt3.gif",
         "width":"104px",
         "height":"80px"
        },
		"dlc":{  
         "height":"100px",
         "url":"https://i.imgur.com/GIfMPSz.jpg",
         "width":"100px"
        },
	 	"docil":{  
         "height":"124px",
         "url":"http://i.imgur.com/4o2FglN.png",
         "width":"128px"
        },
		"dollynho":{  
         "url":"https://i.imgur.com/66UwC9Q.jpg",
         "width":"108px",
         "height":"81px"
        },
		"dopado":{  
         "url":"https://i.imgur.com/DQI1o7D.gif",
         "width":"120px",
         "height":"120px"
        },
		"dragão":{  
         "url":"https://i.imgur.com/b79bIsm.png",
         "width":"107px",
         "height":"86px"
        },
		"dribe":{  
         "url":"https://i.imgur.com/IfVOE3J.jpg",
         "width":"106px",
         "height":"52px"
        },
		"dribe2":{  
         "height":"90px",
         "url":"https://i.imgur.com/aUkbohX.jpg",
         "width":"55px"
        },
		"dribe3":{  
         "height":"79px",
         "url":"https://i.imgur.com/57FtsgX.jpg",
         "width":"97px"
        },
		"dribe4":{  
         "width":"136px",
      	 "height":"90px",
      	 "url":"https://i.imgur.com/CjizyLK.jpg",
        },
		"empolgante":{  
         "height":"130px",
         "url":"https://i.imgur.com/R3HHVD2.jpg",
         "width":"130px"
        },
		"em":{  
         "height":"99px",
         "url":"https://i.imgur.com/qlMQyza.jpg",
         "width":"117px"
        },
		"emsm":{  
         "url":"https://i.imgur.com/aDhjPXx.jpg",
         "width":"59px",
         "height":"80px"
        },
		"emsme":{  
         "height":"59px",
         "url":"https://i.imgur.com/pfQVT5U.jpg",
         "width":"79px"
        },
		"engraçado":{  
         "height":"91px",
         "url":"http://i.imgur.com/n6c80tr.jpg",
         "width":"120px"
        },
		"erou":{  
         "url":"https://i.imgur.com/4wrakbp.jpg",
         "width":"139px",
         "height":"104px"
        },
		"euquis":{  
         "url":"https://i.imgur.com/iZdZPPd.jpg",
         "width":"81px",
         "height":"104px"
        },
		"fafa":{  
         "url":"https://i.imgur.com/m8ZopBV.gif",
         "width":"136px",
         "height":"141px"
        },
		"faleceu":{  
         "height":"51px",
         "url":"https://i.imgur.com/vZE62y1.jpg",
         "width":"69px"
        },
	 	"faustão":{  
         "url":"http://i.imgur.com/SX0OANN.gif",
         "width":"123px",
         "height":"140px"
        },
		"ficouoh":{  
         "url":"http://i.imgur.com/8y2SXIF.png",
         "width":"138px",
         "height":"104px"
        },
	 	"ficouoh":{  
         "url":"https://i.imgur.com/h1ZFm2P.jpg",
         "width":"79px",
         "height":"55px"
        },
		"foda-se":{  
         "height":"90px",
         "url":"https://i.imgur.com/8pBXLn7.gif",
         "width":"106px"
        },
		"foda-se2":{  
         "height":"90px",
         "url":"https://i.imgur.com/bCYVoEx.jpg",
         "width":"126px"
        },
		"foda-se3":{  
         "height":"80px",
         "url":"https://i.imgur.com/0EfQWMN.jpg",
         "width":"100px"
        },
		"foda-se4":{  
         "height":"150px",
         "url":"http://i.imgur.com/X7HEXSX.png",
         "width":"250px"
        },
		"foda.se":{  
         "height":"120px",
         "url":"https://i.imgur.com/Ju4rLQA.jpg",
         "width":"120px"
        },
		"fodace":{  
         "url":"https://i.imgur.com/mbHJvoR.gif",
         "width":"120px",
         "height":"120px"
        },
		"fodase":{  
         "height":"58px",
         "url":"https://i.imgur.com/j1cSxm0.jpg",
         "width":"77px"
        },
		"fofão":{  
         "url":"https://i.imgur.com/8Mq3tPR.gif",
         "width":"120px",
         "height":"90px"
        },
		"freestep":{  
         "height":"90px",
         "url":"https://i.imgur.com/bfDKHgM.gif",
         "width":"160px"
        },
	 	"frio":{  
         "url":"http://i.imgur.com/noV17ej.png",
         "width":"120px",
         "height":"166px"
        },
		"gato":{  
         "height":"70px",
         "url":"https://i.imgur.com/wRI10nK.gif",
         "width":"102px"
        },
		"gente":{  
         "height":"86px",
         "url":"https://i.imgur.com/ORjnzfn.jpg",
         "width":"64px"
        },
		"graça":{  
         "height":"100px",
         "url":"https://i.imgur.com/4f7LR3B.jpg",
         "width":"120px"
        },
	 	"gorila":{  
         "height":"116px",
         "url":"http://i.imgur.com/uX0nWaU.png",
         "width":"115px"
        },
	 	"hack":{  
         "height":"141px",
         "url":"http://i.imgur.com/0jO2pig.png",
         "width":"137px"
        },
		"hino":{  
         "height":"108px",
         "url":"http://i.imgur.com/sued5LA.gif",
         "width":"120px"
        },
		"hjn":{  
         "height":"63px",
         "url":"https://i.imgur.com/SoZkcP3.jpg",
         "width":"84px"
        },
		"hmm":{  
         "height":"100px",
         "url":"https://i.imgur.com/ofTagdg.gif",
         "width":"120px"
        },
		"hmm2":{  
         "height":"100px",
         "url":"https://i.imgur.com/4PzgMep.jpg",
         "width":"100px"
        },
		"hu3":{  
         "height":"90px",
         "url":"https://i.imgur.com/wiQ0cyG.gif",
         "width":"144px"
        },
		"hu3br":{  
         "height":"93px",
         "url":"https://i.imgur.com/lM5EMUZ.jpg",
         "width":"90px"
        },
		"huera":{  
         "height":"100px",
         "url":"https://i.imgur.com/eGdbSgO.jpg",
         "width":"120px"
        },
		"idai":{  
         "height":"80px",
         "url":"https://i.imgur.com/OgHQCry.jpg",
         "width":"90px"
        },
		"idiota":{  
         "url":"https://i.imgur.com/ocsGCQv.gif",
         "width":"150px",
         "height":"70px"
        },
		"infarto":{  
         "url":"https://i.imgur.com/3hvzwln.jpg",
         "width":"140px",
         "height":"114px"
        },
		"istudu":{  
         "url":"https://i.imgur.com/XuJbgWk.gif",
         "width":"150px",
         "height":"70px"
        },
		"invitation":{  
         "url":"http://i.imgur.com/3ZaIiJZ.png",
         "width":"300px",
         "height":"50px"
        },
		"jachega":{  
         "height":"120px",
         "url":"https://i.imgur.com/aTmTdas.png",
         "width":"100px"
        },
		"jailson":{  
         "url":"https://i.imgur.com/dVthkoQ.gif",
         "width":"104px",
         "height":"80px"
        },
		"jailson2":{  
         "url":"https://i.imgur.com/sLlX5B2.jpg",
         "width":"84px",
         "height":"84px"
        },
		"jailson3":{  
         "url":"https://i.imgur.com/XfJNTVs.jpg",
         "width":"61px",
         "height":"71px"
        },
		"jailson4":{  
         "url":"https://i.imgur.com/G08Oq6x.gif",
         "width":"116px",
         "height":"89px"
        },
		"jureg":{  
         "height":"112px",
         "url":"https://i.imgur.com/SDzmH3a.jpg",
         "width":"199px"
        },
		"jureg2":{  
         "height":"111px",
         "url":"http://i.imgur.com/3R2VGem.png",
         "width":"196px"
        },
		"jureg3":{  
         "height":"103px",
         "url":"https://i.imgur.com/V4Ly6IE.png",
         "width":"199px"
        },
		"jureg4":{  
         "height":"105px",
         "url":"http://i.imgur.com/Yb3TB0p.png",
         "width":"195px"
        },
		"léostronda":{  
         "height":"51px",
         "url":"https://i.imgur.com/tsv7zX4.png",
         "width":"259px"
        },
		"legal":{  
         "height":"56px",
         "url":"https://i.imgur.com/NAvDJFl.jpg",
         "width":"75px"
        },
		"lennyface":{  
         "height":"47px",
         "url":"https://i.imgur.com/g4zRJ9C.jpg",
         "width":"108px"
        },
		"ler":{  
         "height":"94px",
         "url":"https://i.imgur.com/dP3k6pR.jpg",
         "width":"240px"
        },
		"linteressa":{  
         "url":"https://i.imgur.com/xhCO25z.gif",
         "width":"147px",
         "height":"70px"
        },
		"madruga":{  
         "url":"https://i.imgur.com/OvDq257.gif",
         "width":"108px",
         "height":"88px"
        },
		"mandanude":{  
         "url":"https://i.imgur.com/PTYLcye.png",
         "width":"131px",
         "height":"90px"
        },
		 "maigode":{
         "height":"90px",
         "url":"https://i.imgur.com/6kZ4Br6.jpg",
         "width":"100px"
        },
         "maigode2":{
         "height":"100px",
         "url":"https://i.imgur.com/n79SjXm.jpg",
         "width":"100px"
        },
		"marcelo":{  
         "height":"100px",
          "url":"https://i.imgur.com/KJ7VuYX.jpg",
          "width":"93px"
        },
		"marreco":{  
         "height":"110px",
         "url":"http://i.imgur.com/VUZxXTX.jpg",
         "width":"152px"
        },
		"marina":{  
         "url":"https://i.imgur.com/UHRpp4d.png",
         "width":"90px",
         "height":"90px"
        },
	 	"marinho":{  
         "url":"http://i.imgur.com/1fi0yJK.png",
         "width":"93px",
         "height":"165px"
        },
		"masc":{  
         "url":"https://i.imgur.com/O49ugVB.png",
         "width":"216px",
         "height":"104px"
        },
		"mehh":{  
         "height":"100px",
         "url":"http://i.imgur.com/6lYPeQO.jpg",
         "width":"100px"
        },
		"meobrigue":{  
         "url":"https://i.imgur.com/HrfUfMS.png",
         "width":"128px",
         "height":"90px"
        },
		"mizeravi":{  
         "height":"82px",
         "url":"https://i.imgur.com/4ILWtwV.png",
         "width":"54px"
        },
		"moitai":{  
         "height":"56px",
         "url":"https://i.imgur.com/X379iNh.png",
         "width":"330px"
        },
		"monalicia":{  
         "url":"https://i.imgur.com/35Jrx9b.png",
         "width":"74px",
         "height":"74px"
        },
		"monstrogif":{  
         "url":"https://i.imgur.com/15hqUd0.gif",
         "width":"104px",
         "height":"88px"
        },
		"morre":{  
         "url":"https://i.imgur.com/B100qjp.gif",
         "width":"115px",
         "height":"86px"
        },
		"morrison":{  
         "height":"120px",
         "url":"https://i.imgur.com/6g3PA6d.gif",
         "width":"120px"
        },
		"nãosei":{  
         "height":"70px",
         "url":"https://i.imgur.com/QoPAHYd.png",
         "width":"80px"
        },
		"nadave":{  
         "url":"https://i.imgur.com/IydoxRH.png",
         "width":"130px",
         "height":"72px"
        },
		"nao1":{  
         "height":"90px",
         "url":"https://i.imgur.com/30Yl6Hk.jpg",
         "width":"100px"
        },
		"nao":{  
         "url":"https://i.imgur.com/XGAXb3O.png",
         "width":"90px",
         "height":"84px"
        },
		"negócio":{  
         "height":"88px",
         "url":"https://i.imgur.com/rPIhhjM.gif",
         "width":"104px"
        },
		"nentendi":{  
         "url":"https://i.imgur.com/AcN6tOG.gif",
         "width":"106px",
         "height":"80px"
        },
		"nossa":{  
         "height":"120px",
         "url":"https://i.imgur.com/FgrAWii.jpg",
         "width":"120px"
        },
		"nudes":{  
         "height":"103px",
         "url":"https://i.imgur.com/pvUWCt7.jpg",
         "width":"207px"
        },
		"numsei":{  
         "url":"https://i.imgur.com/Hh0RnJH.gif",
         "width":"150px",
         "height":"70px"
        },
		"observo":{  
         "url":"https://i.imgur.com/XgDXpu5.gif",
         "width":"153px",
         "height":"80px"
        },
		"oco":{  
         "url":"https://i.imgur.com/QSBygqu.png",
         "width":"28px",
         "height":"28px"
        },
		"oco2":{  
         "url":"https://i.imgur.com/xOX01k3.jpg",
         "width":"72px",
         "height":"70px"
        },
		"okne":{  
         "url":"https://i.imgur.com/VkktMNz.gif",
         "width":"68px",
         "height":"65px"
        },
		"olha":{  
         "height":"90px",
         "url":"https://i.imgur.com/5lKVDdL.png",
         "width":"127px"
        },
		"olhaela":{  
         "height":"103px",
         "url":"http://i.imgur.com/LV0jAeu.jpg",
         "width":"120px"
        },
		"ovo":{  
         "height":"90px",
         "url":"https://i.imgur.com/MojsPPc.gif",
         "width":"110px"
        },
		"oxe":{  
         "url":"https://i.imgur.com/6m4EzlB.gif",
         "width":"150px",
         "height":"70px"
        },
		"ozzydeia":{  
         "height":"120px",
         "url":"https://i.imgur.com/YCGImPN.jpg",
         "width":"120px"
        },
		"pão":{  
         "url":"https://i.imgur.com/7TNXE0O.jpg",
         "width":"103px",
         "height":"48px"
        },
		"palhaço":{  
         "url":"https://i.imgur.com/k6D8MdT.png",
         "width":"28px",
         "height":"28px"
        },
		"parabains":{  
         "url":"https://i.imgur.com/biIoQe8.jpg",
         "width":"120px",
         "height":"100px"
        },
		"parede":{  
         "height":"90px",
         "url":"https://i.imgur.com/deJHDnl.gif",
         "width":"160px"
        },
	 	"patrão":{  
         "height":"127px",
         "url":"http://i.imgur.com/U1gaFRq.png",
         "width":"153px"
        },
		"pclixo":{  
         "height":"50px",
         "url":"https://i.imgur.com/aVrNvoO.gif",
         "width":"50px"
        },
		"penes":{  
         "height":"37px",
         "url":"https://i.imgur.com/ypzUakJ.png",
         "width":"71px"
        },
		"penes2":{  
         "height":"225px",
         "url":"https://i.imgur.com/b3Vv0RI.png",
         "width":"105"
        },
		"pesquisa":{  
         "url":"https://i.imgur.com/hlOb17t.jpg",
         "width":"261px",
         "height":"62px"
        },
		"pingu":{  
         "height":"107px",
         "url":"http://i.imgur.com/Nzn0ZXP.png",
         "width":"143px"
        },
		"pistola":{  
         "height":"120px",
         "url":"https://i.imgur.com/Z9to5Nl.png",
         "width":"100px"
        },
		"pnc":{  
         "height":"87px",
         "url":"http://i.imgur.com/67U9AHV.jpg",
         "width":"120px"
        },
		"pocaralho":{  
         "height":"90px",
         "url":"https://i.imgur.com/NVgxpMW.jpg",
         "width":"110px"
        },
		"poder":{  
         "height":"60px",
         "url":"https://i.imgur.com/DxHp6Ey.jpg",
         "width":"133px"
        },
		"poha":{  
         "height":"79px",
         "url":"http://i.imgur.com/dJlhrZE.gif?1",
         "width":"140px"
        },
		"popeye":{  
         "width":"123px",
      	 "height":"92px",
      	 "url":"https://i.imgur.com/HvCD34r.gif",
        },
		"porai":{  
         "height":"110px",
         "url":"http://i.imgur.com/J6HBRW0.jpg",
         "width":"130px"
        },
		"prerigo":{  
         "height":"78px",
         "url":"https://i.imgur.com/rdzc9ca.png",
         "width":"104px"
        },
		"providencia":{  
         "height":"104px",
         "url":"https://i.imgur.com/HmB60BT.png",
         "width":"83px"
        },
		"psg":{  
         "url":"https://i.imgur.com/7DGHT1Z.jpg",
         "width":"161px",
         "height":"90px"
        },
		"punheta":{  
         "height":"97px",
         "url":"http://i.imgur.com/1ytVUXI.jpg",
         "width":"130px"
        },
	 	"punhetão":{  
         "height":"106px",
         "url":"http://i.imgur.com/O4ExeEm.png",
         "width":"134px"
        },
		"punheteiro":{  
         "url":"https://i.imgur.com/OVayNxL.png",
         "width":"142px",
         "height":"80px"
        },
		"putavida":{  
         "height":"88px",
         "url":"https://i.imgur.com/dhnwM5I.gif",
         "width":"104px"
        },
		"puto":{  
         "url":"https://i.imgur.com/v9h01r1.png",
         "width":"100px",
         "height":"100px"
        },
		"q":{  
         "height":"100px",
         "url":"https://i.imgur.com/cZnygtn.jpg",
         "width":"90px"
        },
		"q2":{  
         "height":"120px",
         "url":"https://i.imgur.com/df4twj2.png",
         "width":"100px"
        },
		"q3":{  
         "height":"90px",
         "url":"http://i.imgur.com/C8fXWcb.jpg",
         "width":"90px"
        },
		"qponto":{  
         "height":"100px",
         "url":"https://imgur.com/4NdIVTN.jpg",
         "width":"130px"
        },
		"quelixo":{  
         "height":"80px",
         "url":"https://i.imgur.com/g9IKzd1.jpg",
         "width":"150px"
        },
		"queviaje":{  
         "height":"80px",
         "url":"https://i.imgur.com/1Pp17HT.jpg",
         "width":"150px"
        },
		"r10":{  
         "height":"70px",
         "url":"https://i.imgur.com/yXY2KHX.jpg",
         "width":"128px"
        },
		"r10secret":{  
         "height":"70px",
         "url":"https://i.imgur.com/o0Ha07A.jpg",
         "width":"128px"
        },
		"rapariga":{  
         "height":"98px",
         "url":"https://i.imgur.com/puyTsuO.jpg",
         "width":"172px"
        },
		"recalque":{  
         "height":"90px",
         "url":"https://i.imgur.com/BvOMvP9.gif",
         "width":"118px"
        },
		"referencia":{  
         "height":"78px",
         "url":"http://i.imgur.com/SEfSWsq.jpg",
         "width":"140px"
        },
		"rica":{  
         "height":"88px",
         "url":"https://i.imgur.com/hzqgxR6.gif",
         "width":"102px"
        },
		"rosque":{  
         "height":"69px",
         "url":"https://i.imgur.com/3bs2prg.jpg",
         "width":"92px"
        },
		"sai":{  
         "url":"https://i.imgur.com/I80DvSW.png",
         "width":"104px",
         "height":"50px"
        },
		"saxguy":{  
         "height":"92px",
         "url":"https://i.imgur.com/86nV3Ms.gif",
         "width":"123px"
        },
		"sefoda":{  
         "height":"100px",
         "url":"https://i.imgur.com/IDHE3Ve.gif",
         "width":"120px"
        },
		"sefoda2":{  
         "height":"120px",
         "url":"https://i.imgur.com/igDZYOt.gif",
         "width":"120px"
        },
		"sefoda3":{  
         "height":"100px",
         "url":"https://i.imgur.com/WcV2IVL.gif",
         "width":"120px"
        },
		"sefodeu":{  
         "height":"90px",
         "url":"https://i.imgur.com/S51VdIi.jpg",
         "width":"113px"
        },
		"sefuder":{  
         "height":"100px",
         "url":"https://i.imgur.com/34K5mb7.jpg",
         "width":"120px"
        },
		"sexo":{  
         "height":"80px",
         "url":"https://i.imgur.com/SXXcqnB.gif",
         "width":"120px"
        },
		"sim":{  
         "url":"https://i.imgur.com/NL9o8ng.gif",
         "width":"104px",
         "height":"88px"
        },
		"strondou":{  
         "height":"100px",
         "url":"https://i.imgur.com/18jBXx7.jpg",
         "width":"120px"
        },
		"suicídio":{  
         "height":"55px",
         "url":"https://i.imgur.com/SpsBBF8.jpg",
         "width":"75px"
        },
		"tacerto":{  
         "url":"https://i.imgur.com/6dBnnKB.gif",
         "width":"110px",
         "height":"81px"
        },
		"tacry":{  
         "url":"https://i.imgur.com/WrYcJtP.jpg",
         "width":"104px",
         "height":"50px"
        },
		"tainá":{  
         "height":"120px",
         "url":"https://i.imgur.com/umm8KTs.jpg",
         "width":"120px"
        },
		"talento":{  
         "height":"90px",
         "url":"https://i.imgur.com/qBikFj6.gif",
         "width":"185px"
        },
		"taquerendo":{  
         "url":"https://dl.dropboxusercontent.com/s/q9i6gdl6f8ylepi/seicome.gif",
         "width":"104px",
         "height":"100px"
        },
		"tesão":{  
         "height":"56px",
         "url":"https://i.imgur.com/I0NsPEe.jpg",
         "width":"75px"
        },
		"tom":{  
         "height":"113px",
         "url":"https://i.imgur.com/dLxtSmc.png",
         "width":"200px"
        },
		"treta":{  
         "url":"https://i.imgur.com/3XiQPSH.gif",
         "width":"54px",
         "height":"68px"
        },
	 	"treta2":{  
         "url":"http://i.imgur.com/CPnPfcN.png",
         "width":"149px",
         "height":"112px"
        },
		"uau":{  
         "url":"https://i.imgur.com/InFJRi3.gif",
         "width":"108px",
         "height":"88px"
        },
		"util":{  
         "height":"90px",
         "url":"https://i.imgur.com/InUkCys.gif",
         "width":"95px"
        },
		"vai":{  
         "height":"80px",
         "url":"https://i.imgur.com/rmxse7j.png",
         "width":"145px"
        },
		"vaicry":{  
         "url":"https://i.imgur.com/05uFYdE.png",
         "width":"104px",
         "height":"50px"
        },
		"vaifodase":{  
         "height":"83px",
         "url":"https://i.imgur.com/b3zJklr.jpg",
         "width":"84px"
        },
		"vergonha":{  
         "height":"110px",
         "url":"https://i.imgur.com/XF5PEKF.png",
         "width":"110px"
        },
		"vergonha2":{  
         "height":"80px",
         "url":"http://i.imgur.com/VfGcch7.jpg",
         "width":"110px"
        },
		"viadão":{  
         "height":"80px",
         "url":"https://i.imgur.com/t1YAxJp.jpg",
         "width":"107px"
        },
		"viadão2":{  
         "height":"105px",
         "url":"http://i.imgur.com/9ZfaeCS.png",
         "width":"181px"
        },
		"viadão3":{  
         "height":"108px",
         "url":"http://i.imgur.com/FpkrrMJ.png",
         "width":"150px"
        },
		"viadão4":{  
         "height":"108px",
         "url":"http://i.imgur.com/E8k4HrO.jpg",
         "width":"144px"
        },
		"viadão5":{  
         "height":"164px",
         "url":"http://i.imgur.com/SoDMUNv.png",
         "width":"131px"
        },
		"viadão6":{  
         "height":"101px",
         "url":"http://i.imgur.com/HbVBm9m.jpg",
         "width":"144px"
        },
		"viadão7":{  
         "height":"102px",
         "url":"http://i.imgur.com/WdEOT4n.png",
         "width":"166px"
        },
		"viadão8":{  
         "height":"102px",
         "url":"http://i.imgur.com/SuzvjHd.png",
         "width":"151px"
        },
		"viadão9":{  
         "height":"124px",
         "url":"http://i.imgur.com/mJpxSjk.gif",
         "width":"165px"
        },
	 	"viadão10":{  
         "height":"107px",
         "url":"http://i.imgur.com/10nyxoc.png",
         "width":"197px"
        },
	 	"viadão11":{  
         "height":"113px",
         "url":"http://i.imgur.com/lFKJNft.jpg",
         "width":"196px"
        },
		"viadãobonito":{  
         "height":"72px",
         "url":"https://i.imgur.com/zkO4uuS.jpg",
         "width":"95px"
        },
		"viadagem":{  
         "height":"89px",
         "url":"https://i.imgur.com/wXmhCyx.png",
         "width":"101px"
        },
		"warlocked":{  
         "height":"65px",
         "url":"http://i.imgur.com/lADgrIQ.jpg?1",
         "width":"326px"
        },
	 	"war2":{  
         "height":"127x",
         "url":"http://i.picasion.com/resize82/d066dde436bc158651ebb80bd85a2f97.gif",
         "width":"130px"
        },
		"xablau":{  
         "url":"https://i.imgur.com/uEHQSrA.gif",
         "width":"70px",
         "height":"48px"
        },
		"zoeira":{  
         "url":"https://i.imgur.com/zVFnkQU.png",
         "width":"90px",
         "height":"80px"
        },
		"zoeiro":{  
         "height":"57px",
         "url":"https://i.imgur.com/jBr1NaT.jpg",
         "width":"58px"
        }
   },
	 "Futebol" : {
      "barcelona":{  
         "url":"https://i.imgur.com/OXc6mzV.png",
         "width":"31px",
         "height":"35px"
      },
      "sp":{  
         "url":"https://i.imgur.com/gSKtVby.png",
         "width":"31px",
         "height":"35px"
      },
      "cruzeiro":{  
         "url":"https://i.imgur.com/822pXUd.png",
         "width":"31px",
         "height":"35px"
      },
      "santos":{  
         "url":"https://i.imgur.com/MHvxHE3.png",
         "width":"31px",
         "height":"35px"
      },
      "realmadrid":{  
         "url":"https://i.imgur.com/Qjk3CHM.png",
         "width":"31px",
         "height":"35px"
      },
      "palmeiras":{  
         "url":"https://i.imgur.com/nXnIgUg.png",
         "width":"31px",
         "height":"35px"
      },
      "inter":{  
         "url":"https://i.imgur.com/1CAyN4A.png",
         "width":"31px",
         "height":"35px"
      },
      "flamengo":{  
         "url":"https://i.imgur.com/U8bzkTC.png",
         "width":"31px",
         "height":"35px"
      },
      "gremio":{  
         "url":"https://i.imgur.com/RIbNpmy.png",
         "width":"31px",
         "height":"35px"
      },
      "corinthians":{  
         "url":"https://i.imgur.com/VRIe1j5.png",
         "width":"31px",
         "height":"35px"
      }
  },
  "Música" : {
     "afrojack":{
        "url":"http://i.imgur.com/ZTL9rtk.png",
        "width":"75px",
        "height":"12px"
     },
     "alesso":{
        "url":"http://i.imgur.com/WV3UkiQ.png",
        "width":"70px",
        "height":"23px"
     },
     "arminvanbuuren":{
        "url":"http://i.imgur.com/1gi73aE.png",
        "width":"74px",
        "height":"30px"
     },
     "avicii":{
         "url":"http://i.imgur.com/Y7jwkMz.png",
         "width":"75px",
         "height":"34px"
      },
      "bassnation":{
         "url":"http://i.imgur.com/GYHVvIX.png",
         "width":"35px",
         "height":"35px"
      },
      "calvinharris":{
         "url":"http://i.imgur.com/oCGqAIz.png",
         "width":"75px",
         "height":"32px"
      },
      "deadmau5":{
         "url":"http://i.imgur.com/pM3id2o.png",
         "width":"48px",
         "height":"35px"
      },
      "dondiablo":{
         "url":"http://i.imgur.com/ks45L1M.png",
         "width":"75px",
         "height":"31px"
      },
      "edmcity":{
         "url":"http://i.imgur.com/xeppKAf.png",
         "width":"75px",
         "height":"33px"
      },
      "hardwell":{
         "url":"http://i.imgur.com/vbovXXJ.png",
         "width":"74px",
         "height":"15px"
      },
      "kdrew":{
         "url":"http://i.imgur.com/aNq3yFr.png",
         "width":"75px",
         "height":"18px"
      },
      "knifeparty":{
         "url":"http://i.imgur.com/XTiGAbN.png",
         "width":"36px",
         "height":"35px"
      },
      "krewella":{
         "url":"http://i.imgur.com/Bmh536K.png",
         "width":"72px",
         "height":"15px"
      },
      "martingarrix":{
         "url":"http://i.imgur.com/uFPUJbD.png",
         "width":"44px",
         "height":"35px"
      },
      "ncs":{
         "url":"http://i.imgur.com/DCp0j66.png",
         "width":"75px",
         "height":"32px"
      },
      "nervo":{
         "url":"http://i.imgur.com/Bl4fA7p.png",
         "width":"75px",
         "height":"21px"
      },
      "nickyromero":{
         "url":"http://i.imgur.com/Y2M7C5Y.png",
         "width":"67px",
         "height":"35px"
      },
      "davidguetta":{
         "url":"http://i.imgur.com/YG3L9Zn.png",
         "width":"80px",
         "height":"31px"
      },
      "plugdj":{
         "url":"http://i.imgur.com/e5ZTfvj.png",
         "width":"33px",
         "height":"35px"
      },
      "proximity":{
         "url":"http://i.imgur.com/QSdXIPY.png",
         "width":"26px",
         "height":"35px"
      },
      "rehab":{
         "url":"http://i.imgur.com/0IXROCz.png",
         "width":"75px",
         "height":"35px"
      },
      "showtek":{
         "url":"http://i.imgur.com/Sky8x4t.png",
         "width":"75px",
         "height":"22px"
      },
      "skrillex":{
         "url":"http://i.imgur.com/FeWO8PB.png",
         "width":"75px",
         "height":"33px"
      },
      "steveaoki":{
         "url":"http://i.imgur.com/V2DKyGR.png",
         "width":"75px",
         "height":"30px"
      },
      "prodigy":{
         "url":"http://i.imgur.com/aTK722r.png",
         "width":"75px",
         "height":"22px"
      },
      "tiesto":{
         "url":"http://i.imgur.com/oD4IarB.png",
         "width":"44px",
         "height":"35px"
      },
      "trapcity":{
         "url":"http://i.imgur.com/Z2cX62i.png",
         "width":"75px",
         "height":"31px"
      },
      "virtualriot":{
         "url":"http://i.imgur.com/b57tQFx.png",
         "width":"53px",
         "height":"35px"
      },
      "zedd":{
         "url":"http://i.imgur.com/6aJ09Bl.png",
         "width":"75px",
         "height":"25px"
      },
      "zomboy":{
         "url":"http://i.imgur.com/UHNZvFl.png",
         "width":"73px",
         "height":"32px"
      },
      "ladygaga":{
         "url":"http://i.imgur.com/B9t4plI.png",
         "width":"90px",
         "height":"64px"
      },
      "passenger":{
         "url":"http://i.imgur.com/C1lxN54.png",
         "width":"90px",
         "height":"18px"
      },
      "raego":{
         "url":"http://i.imgur.com/MWXHels.png",
         "width":"60px",
         "height":"20px"
      }
   }
};
